prography-dev/prography-homepage-frontend

- src/app/page.tsx
👉 기능 설명
- 제발
👉 요청 및 질문사항
📷 스크린샷
> ✨ 자동배포테스트 2

- src/app/test/page.tsx
- src/app/test/test.module.scss
- src/styles/const.scss
👉 기능 설명
- global color 세팅했습니다~
👉 요청 및 질문사항
- gradient 관련
- 각도 맞는지 + 중단점 확인 필요할 것 같긴 합니다..!
- 공통 색으로 쓰이는 게 아니고, 버튼 단일에서만 쓰인다면 버튼으로 바로 만들어도 될 것 같습니다 ㅎㅎ!
📷 스크린샷
> ✨ global color 세팅 및 예시 버튼 생성

- src/app/page.tsx
- src/components/StyledTest.tsx
- src/components/common/button/Button.scss
- src/components/common/button/Button.tsx
- 버튼 컴포넌트 스타일 작업
👉 기능 설명
- Button.tsx 컴포넌트와 스타일 작업입니다. 
👉 요청 및 질문사항
- common/button/Button 이런식으로 호출하는게 귀찮은거같다. 
- common/index.tsx 파일에 공통 컴포넌트들을 추가하고, 호출할때 `import { Button } from '@/components/common'` 하는건 어떨까?
📷 스크린샷
> ✨ 버튼 컴포넌트 추가

- package.json
- src/utils/axios.ts
- yarn.lock
👉 기능 설명
- axios 모듈 추가
👉 요청 및 질문사항
📷 스크린샷
> 📦 axios 모듈 추가

- package.json
- src/app/page.1280.scss
- src/app/page.scss
- src/app/page.tsx
- src/components/Home/Typo.1280.scss
- src/components/Home/Typo.scss
- src/components/Home/Typo.tsx
- yarn.lock
👉 기능 설명
- 메인페이지에서 타이포 애니메이션 있는 컴포넌트 개발 (모바일 피씨 경계값은 일단 임의로 했습니다.)
👉 요청 및 질문사항
- 근데 공통 컴포넌트 버튼도 반응형으로 해야...?하나...? size로 말고 type으로 해서
📷 스크린샷
> 메인페이지 타이포 컴포넌트 개발

- src/app/test/page.tsx
👉 기능 설명
- 어떤 기능을 개발했는지 설명해 주세요
👉 요청 및 질문사항
📷 스크린샷
> ✨ sf-pro font 예시 추가

- package.json
- src/app/page.1280.scss
- src/app/page.scss
- src/app/page.tsx
- src/components/Home/About.1280.scss
- src/components/Home/About.scss
- src/components/Home/About.tsx
- src/components/Home/OneTeam.1280.scss
- src/components/Home/OneTeam.scss
- src/components/Home/OneTeam.tsx
- src/components/Home/PageRouterButton.1280.scss
- src/components/Home/PageRouterButton.scss
- src/components/Home/PageRouterButton.tsx
- src/components/common/layout/CommonWrapper.scss
- src/components/common/layout/CommonWrapper.tsx
- src/styles/fonts.scss
- yarn.lock
👉 기능 설명
- figma 메인페이지 내 About 컴포넌트 추가
- figma 메인페이지 내 One team 컴포넌트 추가
👉 요청 및 질문사항
- 지선누나가 오늘 카톡에서 언급했던 client 렌더링 관련 부분은 나중에 한번에 리팩토링 하도록 하겠습니다.
- css 컨벤션 (snake or kebab)은 일단 케밥으로 진행했습니다. (향후 필요하면 교체하겠습니다.)
- api 요청이 필요한 부분은 주석 남기도록 하겠습니다.
- 카운팅 값은 더미로 넣어놨고 값이 다를 때 올라가는 속도와 같은 상세한 부분은 메인페이지 전체가 개발 된 이후 디자이너분과 협의하도록 하겠습니다.
📷 스크린샷
> ✨ 메인페이지 내 About / One team 컴포넌트 추가

- src/app/project/page.scss
- src/app/project/page.tsx
- src/components/Layout/header/Header.module.scss
- src/components/Project/PROJECT_DATA.ts
- src/components/Project/ProjectCard.scss
- src/components/Project/ProjectCard.tsx
- src/components/Project/ProjectCardContainer.scss
- src/components/Project/ProjectCardContainer.tsx
- src/components/common/icon/Icon80RoundButton.tsx
- src/styles/colors.scss
- src/styles/const.scss
👉 기능 설명
- Project 페이지 전체 웹 기준 마크업 완료했습니다
- Project에 쓰일 더미데이터 추가했습니다
- header에 z-index, 컬러 팔레트 black 추가했습니다 (편의상)
👉 요청 및 질문사항
- Project Container와 Project 카드들 모달과 연결하는 작업을 같이 하려니 PR 양이 많아질 것 같아서, 우선 이 만큼만 올립니다
- 근데 이거 왜 레이아웃 뭔가 삐뚤어져 있죠..?
📷 스크린샷
> ✨ 페이지 전체 웹 마크업 완료, project 더미데이터 추가

- src/components/common/layout/CommonWrapper.scss
👉 기능 설명
- Common wrapper css값 수정했습니다. (width랑 불필요한 padding들어가있었음)
👉 요청 및 질문사항
- 간략한 내용이어서 생략할게요.
> 🔨 Common wrapper 값 수정

- .eslintrc.js
- next.config.js
- src/apis/project.ts
- src/app/project/page.tsx
- src/components/Layout/header/Header.module.scss
- src/components/Layout/header/Header.tsx
- src/components/Project/Modal.scss
- src/components/Project/Modal.tsx
- src/components/Project/PROJECT_DATA.ts
- src/components/Project/ProjectCard.tsx
- src/components/Project/ProjectCardContainer.tsx
👉 기능 설명
- ProjectCard에 쓰일 타입 별도 파일로 뺐습니다 (추후 api 연동 시 활용)
- 카드 - 모달 연결했습니다. id는 프로젝트 제목으로 설정했습니다~
- modal 마크업 브랜치였는데,, 로직을 많이 손대고 정작 마크업은 PR이 길어질 것 같아 중간에 멈춥니다..! 새 브랜치 파서 이어 할게요~
👉 요청 및 질문사항
📷 스크린샷
> ✨ card - modal 연결, header css 세부 수정, data type 분리

- src/app/page.module.scss
- src/app/page.tsx
- src/app/page_1280.module.scss
- src/components/Home/About.module.scss
- src/components/Home/About.tsx
- src/components/Home/About_1280.module.scss
- src/components/Home/OneTeam.module.scss
- src/components/Home/OneTeam.tsx
- src/components/Home/OneTeam_1280.module.scss
- src/components/Home/PageRouterButton.module.scss
- src/components/Home/PageRouterButton.tsx
- src/components/Home/PageRouterButton_1280.module.scss
- src/components/Home/Schedule.module.scss
- src/components/Home/Schedule.tsx
- src/components/Home/Schedule_1280.module.scss
- src/components/Home/Typo.module.scss
- src/components/Home/Typo.tsx
- src/components/Home/Typo_1280.module.scss
- src/components/common/layout/CommonWrapper.module.scss
- src/components/common/layout/CommonWrapper.tsx
👉 기능 설명
- scss 모듈화 시키고 컨벤션 수정했습니다.
👉 요청 및 질문사항
- 하....
> 🔨 scss module 수정

- package.json
- src/app/page.module.scss
- src/app/page.tsx
- src/app/page_1280.module.scss
- src/components/Home/Project.scss
- src/components/Home/Project.tsx
- src/components/Home/ProjectCard.module.scss
- src/components/Home/ProjectCard.tsx
- src/components/Home/ProjectCard_1280.module.scss
- src/utils/formatGeneration.ts
- src/utils/isPcDevice.ts
- yarn.lock
👉 기능 설명
- 프로젝트 라우팅 버튼 추가
- swiper package 추가
- 스와이퍼를 활용한 pc/mobile별 swiper 추가
- 메인페이지 하단에 프로덕션에 필요하지 않는 코드 제거
👉 요청 및 질문사항
- 일단 Pc인지 모바일인지 처음에 확인하고 그 이후론 체크 안합니다. (향후 resize해서 추가 할게요)
- 프로젝트 클릭 시 프로젝트 모달 뜨는 부분은 지선누나꺼 머지 이후로 진행할게요
- 애니메이션 상세한 것은 향후 확인할게요
📷 스크린샷
> ✨ 메인페이지 프로젝트 컴포넌트 추가

- src/components/Layout/header/Header.module.scss
- src/components/Layout/header/Header.tsx
- src/components/common/button/Button.scss
👉 기능 설명
- 모바일 gnb에서 햄버거 클릭 시 밑으로 드래그 하면 opacity 영역에 나가서 position: fixed 추가했습니다
- 공통 버튼 컴포넌트 패딩값 수정했습니다!
> 🔨 GNB css 수정

- next.config.js
- src/apis/statistics.ts
- src/components/Home/About.tsx
- src/utils/axios.ts
👉 기능 설명
- cors에러나서 nextconfig proxy되게 수정했습니다.
- /v1/statistics는 호출 잘되어서 예시코드 넣어놨습니다.
👉 요청 및 질문사항
- reactStrictMode: false했어요. (콘솔 2개뜨는거 보기 싫어서...)
> ✨ 서버 api 호출 세팅 및 예시 추가

- src/app/contact/page.module.scss
- src/app/page_1280.module.scss
- src/components/Home/About.module.scss
- src/components/Home/OneTeam.module.scss
- src/components/Home/OneTeam_1280.module.scss
- src/components/Home/PageRouterButton_1280.module.scss
- src/components/Layout/header/Header.module.scss
- src/components/Layout/header/Header.tsx
- src/components/common/button/Button.scss
- src/components/common/donation/AsanDonation.tsx
👉 기능 설명
- QA 요청 사항 반영했습니다.
- https://www.notion.so/prography-admin/QA-084b3354ed8b4c3ca9ec1a428b74b323 참고해주세요
👉 요청 및 질문사항
- 슬라이더쪽은 프로젝트 상세 모달 붙히는거하면서 수정 하겠습니다.
> 🔨 1차 메인페이지&common qa 요청사항

- src/apis/member.ts
- src/app/about/page.module.scss
- src/app/about/page.tsx
- src/components/About/CrewList.module.scss
- src/components/About/CrewList.tsx
- src/components/About/MEMBER_DATA.ts
👉 기능 설명
- /about 페이지 상단과 Crew 소개 컴포넌트 작업 
👉 요청 및 질문사항
- 요 PR 이후에 모바일 작업 대응하겠슴다 (제외하고 봐주세요)
- 말풍선 ... 개발 이후에 수정할게요 
📷 스크린샷
> ✨ about 페이지 상단 + Crew 소개 작업

- src/components/Home/Project.tsx
- src/components/Home/ProjectCard.module.scss
- src/components/Home/ProjectCard.tsx
- src/hooks/useMobile.ts
- src/hooks/usePc.ts
- src/hooks/useTablet.ts
- src/utils/debounce.ts
- src/utils/isPcDevice.ts
👉 기능 설명
- 프로젝트 클릭 시 프로젝트 모달이 뜨는 기능 추가
- pc/mobile에 따른 swiper option 및 최대 프로젝트 노출 갯수 추가
- 리사이징 함수 관련 리팩토링
> 🔨 메인페이지 프로젝트 컴포넌트 기능 추가 및 리팩토링

- next.config.js
- src/apis/part.ts
- src/app/page.module.scss
- src/app/page.tsx
- src/app/page_1280.module.scss
- src/components/Home/About.tsx
- src/components/Home/LandingButton.module.scss
- src/components/Home/LandingButton.tsx
- src/components/Home/OneTeam.tsx
- src/components/Home/Project.tsx
- src/components/Home/Typo.tsx
- src/utils/axios.ts
👉 기능 설명
- One team api 서버 호출 했습니다.
- 거기에 서버사이드를 곁들인... 리팩토링 코드입니다.
👉 요청 및 질문사항
- 서버사이드로 돌릴 땐 프론트 proxy가 안먹히는거 같더라고요....
- 서버요청을 했을 때 api를 가져오는 부분인 po, designer... 등이 pre-render되는지 확인하면 될 것 같습니다.
> ✨ One team api 호출 및 서버사이드 렌더링 전환

- global.d.ts
- src/app/layout.tsx
- src/app/page.tsx
- src/components/Home/LandingButton.tsx
- src/utils/triggerGtm.ts
👉 기능 설명
- gtm trigger할 수 있는 기능과 지원버튼에 예시 넣어놨습니다.
- metadata tag 기획나오면 바로 할 수 있도록 메인페이지에 title 예시 넣어놨습니다.
👉 요청 및 질문사항
- 혹시 gtm테스트 가이드 필요할까요?
> ✨ gtm 추가 및 metadata 테스트 추가

- src/app/layout.tsx
- src/app/test/page.tsx
- src/components/Layout/header/Header.module.scss
- src/styles/const.scss
- src/styles/global.css
👉 기능 설명
- 어떤 기능을 개발했는지 설명해 주세요
👉 요청 및 질문사항
📷 스크린샷
> 🔨 햄버거버튼 cursor 추가, font 수정

- src/components/Modal/ModalSkeleton.module.scss
👉 기능 설명
- 스켈레톤 이미지 크기 때문에 실제 image 로딩이 늦어지는 건 아닐까..? 하는 추측에 크기 줄여봤습니다. (기분 탓인지 이미지 로딩이 빨라지긴 했습니다)
👉 요청 및 질문사항
📷 스크린샷
> ✨ skeleton image 크기 변경

- src/apis/generation.ts
- src/apis/session.ts
- src/app/page.tsx
- src/components/Home/LandingButton.tsx
- src/components/Home/Schedule.tsx
- src/utils/axios.ts
- src/utils/formatDate.ts
👉 기능 설명
- /v1/generations 호출 및 데이터 연동
- /v1/sessions 호출 및 데이터 연동
- axios error handling 코드 추가
👉 요청 및 질문사항
- project관련 코드는 pr#42 완료되고 할게요
> ✨ 홈 스케쥴, 상태 api 연동

- src/components/Home/Project.scss
- src/components/Home/Project.tsx
- src/components/Home/ProjectCard.module.scss
- src/components/Home/ProjectCard.tsx
- src/components/Home/ProjectCard_1280.module.scss
- src/components/Home/Typo_1280.module.scss
👉 기능 설명
- 프로젝트 api 연동해서 적용했습니다.
- Swiper css 수정 및 js option 수정했습니다.
> ✨ 프로젝트 슬라이더 api 연동 및 리팩토링

- src/components/Modal/ModalCrew.module.scss
- src/components/Modal/ModalCrew.tsx
- src/components/common/icon/IconSlash.tsx
- src/styles/global.css
👉 기능 설명
- 최소 gap: 14px로 수정
- Crew name / part 사이 slash svg로 교체
👉 요청 및 질문사항
📷 스크린샷
> 🔨 Modal Crew 내 QA 반영

- src/components/Home/Project.tsx
👉 기능 설명
- swiper delay 값 수정 (1ms => 1000ms)
> 🔨 swiper delay 값 수정

- src/components/Modal/ModalSkeleton.module.scss
👉 기능 설명
- 어떤 기능을 개발했는지 설명해 주세요
👉 요청 및 질문사항
📷 스크린샷
> 🔨 이미지 스켈레톤 로딩 box 크기 수정

- src/components/About/CrewList.module.scss
> 🔨 object-fit 값 추가

- src/components/About/CrewList.module.scss
- src/components/Modal/ModalSkeleton.module.scss
👉 기능 설명
-🔨 Crew 사진 objectfit추가
👉 요청 및 질문사항
📷 스크린샷
> 🔨 Crew 사진 objectfit추가

- src/app/about/page.tsx
- src/app/page.tsx
- src/components/About/CrewList.module.scss
> 🔨 css 수정 및 캐싱타임 수정

- src/app/[...not_found]/page.module.scss
- src/app/[...not_found]/page.tsx
- src/app/error.tsx
- src/app/not-found.tsx
👉 기능 설명
- not-found, error 페이지 커스텀 작업
👉 요청 및 질문사항
📷 스크린샷
> ✨ not-found, error 페이지 커스텀

- .eslintrc.js
- src/apis/session.ts
- src/app/layout.tsx
- src/app/page.tsx
- src/components/About/CrewList.tsx
- src/components/Home/LandingButton.tsx
- src/components/Home/Schedule.tsx
- src/components/Layout/header/HeaderComponent.tsx
👉 기능 설명
- crewList에 console.log 삭제
- 세션 스케쥴 분기처리 수정
- GNB 분기처리 수정
- 메인페이지 CTA 분기처리 수정
👉 요청 및 질문사항
- 제가 기획에 대해 잘못 이해한 부분이 있는지...
> 🔨 status에 따른 분기처리 수정

- src/components/About/Culture.module.scss
- src/components/Layout/header/HeaderComponent.module.scss
- src/components/Layout/header/HeaderComponent.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/ModalTitle.module.scss
- src/components/Modal/ModalTitle.tsx
- src/components/Modal/OtherProjects.module.scss
- src/components/Modal/OtherProjects.tsx
- src/components/Project/ProjectCard.module.scss
- src/components/Project/ProjectCardSkeleton.module.scss
- src/components/common/icon/Icon64PageButton.tsx
- src/components/common/icon/Icon80RoundButton.tsx
👉 기능 설명
- qa 디자인 사항 수정
참고
https://www.figma.com/file/zxuifYAO576ZK7yM8ei0t0/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9D%BC%ED%94%BC-%ED%99%88-%EA%B0%9C%ED%8E%B8?type=design&node-id=1008-864&mode=design&t=tPrdHUzg2071LT2Z-0
> 🔨 qa 및 개발요청사항 수정

- src/app/page.tsx
- src/components/Contact/FaqList.tsx
- src/components/Home/LandingButton.tsx
- src/components/Home/OneTeam.tsx
- src/components/Layout/footer/Footer.tsx
- src/components/Layout/header/Header.tsx
👉 기능 설명
- Footer에서 인스타/깃허브 링크 리다이렉트 추가
- gtm trigger 수정(메인페이지 cta버튼, faq버튼)
> 🔨 푸터 링크 추가 및 gtm trigger 이벤트 수정

- src/components/Contact/FaqList.module.scss
👉 기능 설명
-  FAQ content 커서 변경
👉 요청 및 질문사항
📷 스크린샷
> 🔨 FAQ content 커서 변경

- src/apis/session.ts
- src/utils/formatDate.ts
👉 기능 설명
- endDate에서 25일 00:00:00이면 24일로 표기되어야함
- 모든 스케쥴 노출이 아닌 event, recruit만노출
> 🔨 endTime 수정 및 api querystring 수정

- src/components/Layout/header/HeaderComponent.tsx
> ✨ gnb button gtm trigger 추가

- src/apis/project.ts
- src/components/Modal/ModalTitle.tsx
- src/components/Project/PROJECT_DATA.ts
- src/components/Project/ProjectComponents.tsx
- src/components/common/icon/GetIconToUrl.tsx
👉 기능 설명
- socials order 기준 정렬
👉 요청 및 질문사항
📷 스크린샷
> 🔨 socials order 기준 정렬

- src/components/Home/LandingButton.tsx
👉 기능 설명
- 랜딩버튼 form만 열리도록 수정
👉 요청 및 질문사항
📷 스크린샷
> 🔨 랜딩버튼 form만 열리도록 수정

- src/app/layout.tsx
👉 기능 설명
- 두개의 ga 스크립트가 공존해서 데이터가 안잡히네요... 일단 수정했습니다.
> 🔨 gtag관련 스크립트코드 삭재

- src/app/layout.tsx
- src/components/Home/LandingButton.tsx
👉 기능 설명
- gtag관련 스크립트코드 삭제
👉 요청 및 질문사항
📷 스크린샷
> 🔨 gtag관련 스크립트코드 삭제

- src/components/About/CrewList.tsx
- src/components/Modal/OtherProjects.tsx
- src/components/Project/ProjectComponents.tsx
- src/components/common/icon/GetIconToUrl.tsx
> 🔨 trigger key값 수정

- src/components/About/Culture.tsx
👉 기능 설명
- hackerton 부분 텍스트 수정 요청
👉 요청 및 질문사항
- (https://discord.com/channels/1038300757734199377/1168160214906835106)확인해주세요!
> 🔨 about culture 텍스트 수정

- src/components/About/Culture.tsx
> 🔨 해커톤 문구 수정
